import React from 'react'
import CartItem from './components/CartItemFlat'
import TableAdresse from './components/TableAdresse'
import InputFlat from './components/InputFlat'
import OrderSummary from './components/OrderSummary'
import PaymentInfoForm from './components/paymentInfoForm'
import CheckoutWrapper from './components/CheckoutWrapper'
import Acknowledgement from './pages/Acknowledgement'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import UserProfile from './pages/UserProfile'
import StoreFrontDarkNav from './tailwind/ecommerce/page-examples/storefront-pages/StoreFrontDarkNav'
import StoreFrontWithImages from './tailwind/ecommerce/page-examples/storefront-pages/StoreFrontWithImages'
import StoreFrontWithTestimonials from './tailwind/ecommerce/page-examples/storefront-pages/StoreFrontWithTestimonials'
import StoreFrontWithTiles from './tailwind/ecommerce/page-examples/storefront-pages/StoreFrontWithTiles'
import ShoppingCardWithGrid from './tailwind/ecommerce/page-examples/shopping-cart-pages/ShoppingCardWithGrid'
import ShoppingCardWithRelatedProducts from './tailwind/ecommerce/page-examples/shopping-cart-pages/ShoppingCardWithRelatedProducts'
import ShoppingCardWithSummary from './tailwind/ecommerce/page-examples/shopping-cart-pages/ShoppingCardWithSummary'
import ProductsPageWithExpandable from './tailwind/ecommerce/page-examples/product-pages/ProductsPageWithExpandable'
import ProductsPageWithFeatured from './tailwind/ecommerce/page-examples/product-pages/ProductsPageWithFeatured'
import ProductsPageWithGrid from './tailwind/ecommerce/page-examples/product-pages/ProductsPageWithGrid'
import ProductsPageWithRelated from './tailwind/ecommerce/page-examples/product-pages/ProductsPageWithRelated' // use thgsi for youshop
import ProductsPageWithTabs from './tailwind/ecommerce/page-examples/product-pages/ProductsPageWithTabs'
import OrderHistory from './tailwind/ecommerce/page-examples/order-history-pages/OrderHistory'
import OrderHistoryWithActions from './tailwind/ecommerce/page-examples/order-history-pages/OrderHistoryWithActions'
import OrderHistoryWithList from './tailwind/ecommerce/page-examples/order-history-pages/OrderHistoryWithList'
import OrderHistoryWithPanel from './tailwind/ecommerce/page-examples/order-history-pages/OrderHistoryWithPanel'
import OrderHistoryWithTables from './tailwind/ecommerce/page-examples/order-history-pages/OrderHistoryWithTables'
import OrderDetailsFull from './tailwind/ecommerce/page-examples/order-detail-pages/OrderDetailsFull'
import OrderDetailsWithBars from './tailwind/ecommerce/page-examples/order-detail-pages/OrderDetailsWithBars'
import OrderDetailsWithProgress from './tailwind/ecommerce/page-examples/order-detail-pages/OrderDetailsWithProgress'
import CheckoutMultiStep from './tailwind/ecommerce/page-examples/checkout-pages/CheckoutMultiStep'
import CheckoutWithOverlay from './tailwind/ecommerce/page-examples/checkout-pages/CheckoutWithOverlay'
import CheckoutWithSidebar from './tailwind/ecommerce/page-examples/checkout-pages/CheckoutWithSidebar'
import CheckoutWithSplit from './tailwind/ecommerce/page-examples/checkout-pages/CheckoutWithSplit'
import CheckoutWithSummary from './tailwind/ecommerce/page-examples/checkout-pages/CheckoutWithSummary'
import CategorySimple from './tailwind/ecommerce/page-examples/category-pages/CategorySimple'
import CategoryWithGrid from './tailwind/ecommerce/page-examples/category-pages/CategoryWithGrid'
import CategoryWithHeader from './tailwind/ecommerce/page-examples/category-pages/CategoryWithHeader'
import CategoryWithPagination from './tailwind/ecommerce/page-examples/category-pages/CategoryWithPagination'
import CategoryWithSidebar from './tailwind/ecommerce/page-examples/category-pages/CategoryWithSidebar'
import HeroesWithPhone from './tailwind/marketing/sections/heroes/HeroesWithPhone'
import HeroesWithBgImage from './tailwind/marketing/sections/heroes/HeroesWithBgImage'
import HeroesCentered from './tailwind/marketing/sections/heroes/HeroesCentered'
import PricingWithComparison from './tailwind/marketing/page-examples/pricing-pages/with_comparison_table'
import HeaderWithCard from './tailwind/marketing/sections/header/HeaderWithCard'
import HeaderWithSelectMenu from './tailwind/marketing/sections/header/HeaderWithSelectMenu'
import HeaderSimple from './tailwind/marketing/sections/header/HeaderSimple'
import CardFull from './tailwind/ecommerce/components/product-lists/CardFull'
import ProductCard from './tailwind/ecommerce/components/product-lists/ProductCard'
import ProductCardBorder from './tailwind/ecommerce/components/product-lists/ProductCardBorder'
import ProductCardScrolling from './tailwind/ecommerce/components/product-lists/ProductCardScrolling'
import TableWithAvatar from './tailwind/application-ui/lists/tables/TableWithAvatar'
import TableWithCheckbox from './tailwind/application-ui/lists/tables/TableWithCheckbox'
import TableWithMobile from './tailwind/application-ui/lists/tables/TableWithMobile'
import SidebarWithIcons from './tailwind/application-ui/navigation/sidebar-navigation/SidebarWithIcons'
import NavbarWithActions from './tailwind/application-ui/navigation/navbars/NavbarWithActions'
import BrandSidebarWithHearder from './tailwind/application-ui/application-shells/sidebar/BrandSidebarWithHearder'
import BrandSidebarWithConstraints from './tailwind/application-ui/application-shells/sidebar/BrandSidebarWithConstraints'
import MultiColumnThree from './tailwind/application-ui/application-shells/multi-column/MultiColumnThree'
import MultiColumnConstrainThree from './tailwind/application-ui/application-shells/multi-column/MultiColumnConstrainThree'
import StatsWithBorder from './tailwind/application-ui/data-display/stats/StatsWithBorder'
import StatsWithIcon from './tailwind/application-ui/data-display/stats/StatsWithIcon'
import DescListTwoColumn from './tailwind/application-ui/data-display/description-lists/DescListTwoColumn'
import DescListStripe from './tailwind/application-ui/data-display/description-lists/DescListStripe'
import CalendarBorderless from './tailwind/application-ui/data-display/calendars/CalendarBorderless'
import FormLabelLeft from './tailwind/application-ui/forms/form-layouts/FormLabelLeft'
import SignInFormSplit from './tailwind/application-ui/forms/sign-in-forms/SignInFormSplit'
import AlertsWithList from './tailwind/application-ui/feedback/alerts/AlertsWithList'
import DropdownsWithIcon from './tailwind/application-ui/elements/dropdowns/with_icons'
import EmptyStatesRecom from './tailwind/application-ui/feedback/empty-states/EmptyStatesRecom'
import ButtonPrimary from './tailwind/application-ui/elements/buttons/primary_buttons'
import HeaderWithFlyouts from './tailwind/marketing/elements/headers/HeaderWithFlyouts'
import HeaderWithStackedLinks from './tailwind/marketing/elements/headers/simple_branded_with_stacked_links'
import FlyoutMenuSimple from './tailwind/marketing/elements/flyout-menus/FlyoutMenuSimple'
import FlyoutMenuWithSolidIcon from './tailwind/marketing/elements/flyout-menus/FlyoutMenuWithSolidIcon'
import ContactList from './tailwind/application-ui/overlays/slide-overs/ContactList'
import CreateObjectsFromExample from './tailwind/application-ui/overlays/slide-overs/CreateObjectsFromExample'
import NotificationSimple from './tailwind/application-ui/overlays/notifications/NotificationSimple'
import SettingsWithNavOverlap from './tailwind/application-ui/page-examples/settings-screens/SettingsWithNavOverlap'
import FeatureWithPanel from './tailwind/marketing/sections/feature-sections/contained_in_panel'
import ContentSection from './tailwind/marketing/sections/content-sections/centered'
import ToggleWithIcons from './tailwind/application-ui/forms/toggles/ToggleWithIcons'
import ModalAlert from './tailwind/application-ui/overlays/modals/ModalAlert'
import FormStacked from './tailwind/application-ui/forms/form-layouts/FormStacked'
import FormTwoColumnCard from './tailwind/application-ui/forms/form-layouts/FormTwoColumnCard'
import FormFullWithCards from './tailwind/application-ui/forms/form-layouts/FormFullWithCards'
import InputWithAddOn from './tailwind/application-ui/forms/input-groups/InputWithAddOn'
import TwoGridIllustration from './tailwind/ecommerce/components/incentives/2x2_grid_with_illustrations'
import ThreeGridIcons from './tailwind/ecommerce/components/incentives/ThreeGridIcons'
import ThreeGridIllustrationWithHeader from './tailwind/ecommerce/components/incentives/3_column_with_illustrations_and_split_header'
import HeadingSimple from './tailwind/application-ui/headings/section-headings/HeadingSimple'
import HeadingWithActions from './tailwind/application-ui/headings/section-headings/HeadingWithActions'
import CardHeading from './tailwind/application-ui/headings/card-headings/simple'
import SectionHeadingWithAction from './tailwind/application-ui/headings/section-headings/SectionHeadingWithAction'
import Banks from './pages/Banks'
import LandingPageWithBg from './tailwind/marketing/page-examples/landing-pages/LandingPageWithBg'
import LandingPageWithHero from './tailwind/marketing/page-examples/landing-pages/LandingPageWithHero'
import LandingPageOffset from './tailwind/marketing/page-examples/landing-pages/LandingPageOffset'
import BrandSidebar from './tailwind/application-ui/application-shells/sidebar/BrandSidebar'
import DropdownSimple from './tailwind/application-ui/elements/dropdowns/simple'
import SlideOversUsers from './tailwind/application-ui/overlays/slide-overs/SlideOversUsers'
import CommandPallets from './tailwind/application-ui/navigation/command-palettes/CommandPallets'
import CommandPalletsSimple from './tailwind/application-ui/navigation/command-palettes/CommandPalletsSimple'
import ProductDetailsPage from './components/ProductsDetails'
import Sample from './sample'
import BadgesRounded from './tailwind/application-ui/elements/badges/BadgesRounded'
import SettingWithTwoColumn from './tailwind/application-ui/page-examples/settings-screens/SettingWithTwoColumn'
import SettingsWithBreadCumb from './tailwind/application-ui/page-examples/settings-screens/SettingsWithBreadCumb'
import SettingsWithSideBarConstraint from './tailwind/application-ui/page-examples/settings-screens/SettingsWithSideBarConstraint'
import SettingsWithTieredSideBar from './tailwind/application-ui/page-examples/settings-screens/SettingsWithTieredSideBar'
import RadioCardGroup from './tailwind/application-ui/forms/radio-groups/RadioCardGroup'
import RadioLineList from './tailwind/application-ui/forms/radio-groups/RadioLineList'
import RadioGroupWithDesc from './tailwind/application-ui/forms/radio-groups/RadioGroupWithDesc'
import RadioGroupRight from './tailwind/application-ui/forms/radio-groups/RadioGroupRight'
import HomeScreenWithMultiColumn from './tailwind/application-ui/page-examples/home-screens/HomeScreenWithMultiColumn'
import HomeScreenWithFullSideBar from './tailwind/application-ui/page-examples/home-screens/HomeScreenWithFullSideBar'
import HomeScreenWithGrid from './tailwind/application-ui/page-examples/home-screens/HomeScreenWithGrid'
import HomeScreenWithNav from './tailwind/application-ui/page-examples/home-screens/HomeScreenWithNav'
import HomeScreenWithCardLayout from './tailwind/application-ui/page-examples/home-screens/HomeScreenWithCardLayout'
import RadioGroupSimpleList from './tailwind/application-ui/forms/radio-groups/RadioGroupSimpleList'
import NotFoundSimple from './tailwind/marketing/feedback/404-pages/NotFoundSimple'
import NotFoundWithLogo from './tailwind/marketing/feedback/404-pages/NotFoundWithLogo'
import DetailScreenWithHeading from './tailwind/application-ui/page-examples/detail-screens/DetailScreenWithHeading'
import UsersTables from './UsersTables'
import SlideOverWithBgOverlay from './tailwind/application-ui/overlays/slide-overs/with_background_overlay'
import CommandPalletWithImgDesc from './tailwind/application-ui/navigation/command-palettes/CommandPalletWithImgDesc'
import SlideOversCreateProj from './tailwind/application-ui/overlays/slide-overs/wide_create_project_form_example'
import RadioGroupSimpleList2 from './tailwind/application-ui/forms/radio-groups/RadioGroupSimpleList2'
import RadioGroupSimpleTable from './tailwind/application-ui/forms/radio-groups/RadioGroupSimpleTable'
import MultiColumnWithStickyHeaders from './tailwind/application-ui/application-shells/multi-column/MultiColumnWithStickyHeaders'

const App = () => {
  return <HomeScreenWithMultiColumn />
  // (
  //   <div>
  //     <main className="bg-white px-10 " >
  //       <section className="min-h-screen" >
  //         <nav className="py-10 mb-12 flex justify-between " >
  //           <h1 className='text-xl font-minion' >developedbynavy</h1>
  //           <ul className="flex items-center" >
  //             <li>
  //               <BsFillMoonStarsFill className='cursor-pointer text-xl text-black ' />
  //             </li>
  //             <li>
  //               <a href="#" className="bg-gradient-to-r from-sky-800 to-indigo-600 p-2 rounded-md text-white text-lg mx-2 ">
  //                 Resume
  //               </a>
  //             </li>
  //           </ul>
  //         </nav>
  //       </section>
  //     </main>
  //   </div>
  // )
}

export default App